[build]
  # Directorio donde Netlify buscará los archivos a publicar
  publish = "docs"  # Los archivos HTML están en "docs"

# Redirección para los recursos CSS
[[redirects]]
  from = "/Css/*"
  to = "/Css/:splat"
  status = 200

# Redirección para los recursos JavaScript
[[redirects]]
  from = "/Js/*"
  to = "/Js/:splat"
  status = 200

# Redirección para los recursos en la carpeta de imágenes y otros archivos estáticos (Assets)
[[redirects]]
  from = "/Assets/*"
  to = "/Assets/:splat"
  status = 200

# Redirección para los recursos en la carpeta Otros (Términos y condiciones, Política de privacidad, etc.)
[[redirects]]
  from = "/Otros/*"
  to = "/Otros/:splat"
  status = 200
